apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: netshoot
  namespace: default
  labels:
    app: netshoot
spec:
    selector:
      matchLabels:
        app: netshoot
  
    template:
      metadata:
        labels:
            app: netshoot
      spec:
        tolerations:
          - key: node-role.kubernetes.io/control-plane
            effect: NoSchedule
        containers:
        - name: netshoot
          image: nicolaka/netshoot
          args:
            - sleep
            - infinity
      
